### ISSUE TITLE
contradiction in README

### ISSUE THREAD

**Issue by xlotlu** [skorokithakis/lektor-thumbnail-generator#1]
Take

> If the original file is smaller than the width you have specified, the file will only be copied, and will not be resized.

and

> Unfortunately, due to the way Lektor's thumbnail system works, files will be scaled up if they're too small.

Looking at the code, the first statement is the actual behaviour. Yet the next one contradicts it?

**Comment by skorokithakis** [comment]
Hmm, great observation, I fixed this in 3a601459b881ff9dab4045f9e6688519984f235b and forgot to remove that paragraph. Will do now, thanks.
